package com.griddynamics.task1;

import java.io.BufferedWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import java.util.Random;

public class FileGenerator {

    private static final String GENERATED_FILE_NAME = "Source.txt";
    private static final String GENERATED_FILE_NAME_FIXED_LINES = "SourceFixed.txt";
    private static final int NUMBERS_COUNT_IN_LINE = 20;
    private static final int LINES_COUNT_IN_FILE_2MB = 20000;
    private static final int MAX_BOUND_NUMBER_2MB = 20000;
    private static final long SIZE = 1024 * 1024 * 4;
    private static final int MAX_BOUND_NUMBER_512MB = 200000;


    public static void main(String[] args) {
        //generateFile(GENERATED_FILE_NAME, NUMBERS_COUNT_IN_LINE, LINES_COUNT_IN_FILE_2MB, MAX_BOUND_NUMBER_2MB);
        //generateFile(GENERATED_FILE_NAME_FIXED_LINES, NUMBERS_COUNT_IN_LINE, 10, 10);
        generateFileWithSize(GENERATED_FILE_NAME, NUMBERS_COUNT_IN_LINE, SIZE, MAX_BOUND_NUMBER_512MB);
    }

    private static void generateFile(String generatedFileName, int numbersCountInLine, int linesCountInFile, int maxBoundNumber) {
        try (BufferedWriter writer = Files.newBufferedWriter(Paths.get(generatedFileName)
                , StandardOpenOption.WRITE, StandardOpenOption.TRUNCATE_EXISTING, StandardOpenOption.CREATE)) {
            for (int i = 1; i <= linesCountInFile; i++) {
                System.out.println("Line #" + i + " of " + linesCountInFile);
                String line = generateLine(numbersCountInLine, maxBoundNumber);
                writer.write(line);
                writer.newLine();
            }

        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private static void generateFileWithSize(String generatedFileName, int numbersCountInLine, long size, int maxBoundNumber) {
        try (BufferedWriter writer = Files.newBufferedWriter(Paths.get(generatedFileName)
                , StandardOpenOption.WRITE, StandardOpenOption.TRUNCATE_EXISTING, StandardOpenOption.CREATE)) {
            long generatedSize = 0;
            while (generatedSize < size) {
                String line = generateLine(numbersCountInLine, maxBoundNumber);
                generatedSize += line.getBytes().length;
                System.out.println("Generated bytes #" + generatedSize + " of " + size);
                writer.write(line);
                writer.newLine();
            }

        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private static String generateLine(int lineLength, int maxBoundNumber) {
        String str = "";
        for (int i = 0; i < lineLength; i++) {
            str += String.valueOf(new Random().nextInt(maxBoundNumber));
        }
        return str;
    }

}